import type { FeaturedProject, Demo } from '../types';

export const GITHUB_USERNAME = 'animeshkundu';
export const LINKEDIN_URL = 'https://www.linkedin.com/in/animeshkundu';
export const FACEBOOK_URL = 'https://www.facebook.com/animesh.kundu';
export const EMAIL = 'anik.edu@gmail.com';

export const FEATURED_PROJECTS: FeaturedProject[] = [
  {
    id: 'mermaid-editor',
    name: 'mermaid-editor',
    title: 'Mermaid Editor',
    description: 'Modern, client-side Mermaid diagram editor with Monaco editor, live preview, pan/zoom controls, and export to PNG/SVG/Markdown. Create flowcharts, sequence diagrams, and 20+ diagram types.',
    language: 'TypeScript',
    technologies: ['React 19', 'Vite', 'Monaco Editor', 'Tailwind CSS', 'shadcn/ui'],
    demoUrl: 'https://animeshkundu.github.io/mermaid-editor',
    githubUrl: 'https://github.com/animeshkundu/mermaid-editor',
    featured: true,
    category: 'web-tools',
    highlights: ['Live Preview', 'Dark Mode', 'Keyboard Shortcuts', '20+ Diagram Types'],
  },
  {
    id: 'oops',
    name: 'oops',
    title: 'Oops',
    description: 'Lightning-fast Rust CLI that fixes command-line typos with 175+ correction rules and sub-50ms startup. 10x faster than Python alternatives with cross-platform support.',
    language: 'Rust',
    technologies: ['Rust', 'CLI', 'Cross-Platform'],
    githubUrl: 'https://github.com/animeshkundu/oops',
    featured: true,
    category: 'cli-tools',
    highlights: ['175+ Rules', 'Sub-50ms Startup', 'Shell Integration', '10x Faster'],
  },
  {
    id: 'pdf-viewer',
    name: 'pdf-viewer',
    title: 'PDF Viewer & Editor',
    description: 'Client-side PDF viewer and editor inspired by macOS Preview. View, annotate, highlight, draw, and edit PDFs entirely in your browser. Zero server dependency, complete privacy.',
    language: 'TypeScript',
    technologies: ['React 19', 'PDF.js', 'pdf-lib', 'Tailwind CSS'],
    demoUrl: 'https://animeshkundu.github.io/pdf-viewer',
    githubUrl: 'https://github.com/animeshkundu/pdf-viewer',
    featured: true,
    category: 'web-tools',
    highlights: ['100% Client-Side', 'Annotations', 'Page Editing', 'Privacy-First'],
  },
  {
    id: 'youtube-audio',
    name: 'youtube-audio',
    title: 'YouTube Audio',
    description: 'Firefox extension to disable video playback on YouTube and listen to audio only. Save bandwidth, battery life, and reduce CPU usage - perfect for music listening while working.',
    language: 'JavaScript',
    technologies: ['WebExtensions API', 'Firefox Add-ons'],
    githubUrl: 'https://github.com/animeshkundu/youtube-audio',
    stars: 167,
    forks: 39,
    featured: true,
    category: 'browser-extensions',
    highlights: ['167+ Stars', 'Save Bandwidth', 'Battery Efficient', 'Firefox Add-on'],
  },
  {
    id: 'gist-preview',
    name: 'gist-preview',
    title: 'Gist Preview',
    description: 'Elegant GitHub Gist renderer with React/JSX live transpilation, responsive previews, fullscreen mode, and smart content-aware rendering for HTML, Markdown, and code.',
    language: 'TypeScript',
    technologies: ['React 19', 'Babel', 'Tailwind CSS', 'Framer Motion'],
    demoUrl: 'https://animeshkundu.github.io/gist-preview',
    githubUrl: 'https://github.com/animeshkundu/gist-preview',
    featured: false,
    category: 'web-tools',
    highlights: ['React/JSX Execution', 'Multi-file Support', 'Shareable URLs'],
  },
  {
    id: 'saz-viewer',
    name: 'saz-viewer',
    title: 'SAZ Viewer',
    description: '100% client-side Fiddler SAZ file viewer. Inspect network sessions with syntax highlighting, multi-tab interface, and secure local processing. Your data never leaves your browser.',
    language: 'TypeScript',
    technologies: ['React 19', 'Vite', 'Tailwind CSS', 'JSZip'],
    demoUrl: 'https://animeshkundu.github.io/saz-viewer',
    githubUrl: 'https://github.com/animeshkundu/saz-viewer',
    featured: false,
    category: 'web-tools',
    highlights: ['100% Client-Side', 'Drag & Drop', 'Syntax Highlighting'],
  },
  {
    id: 'har-viewer',
    name: 'har-viewer',
    title: 'HAR Viewer',
    description: 'Client-side HTTP Archive analyzer with waterfall charts, request filtering, detailed timing visualization, and JSON formatting. Perfect for network debugging without privacy concerns.',
    language: 'TypeScript',
    technologies: ['React 19', 'Zustand', 'Tailwind CSS', 'Web Workers'],
    demoUrl: 'https://animeshkundu.github.io/har-viewer',
    githubUrl: 'https://github.com/animeshkundu/har-viewer',
    featured: false,
    category: 'web-tools',
    highlights: ['Waterfall Charts', '90%+ Test Coverage', 'Web Worker Parsing'],
  },
  {
    id: 'torrent-dl',
    name: 'torrent-dl',
    title: 'Torrent DL',
    description: 'Streaming torrent client for Python - watch while you download! Supports random and incremental seek functionality with automatic VLC playback. Built on pyflix library.',
    language: 'Python',
    technologies: ['Python', 'libtorrent', 'VLC'],
    githubUrl: 'https://github.com/animeshkundu/torrent-dl',
    stars: 33,
    forks: 8,
    featured: false,
    category: 'python-utilities',
    highlights: ['Stream While Download', 'VLC Integration', 'PyPI Package'],
  },
  {
    id: 'pyflix',
    name: 'pyflix',
    title: 'PyFlix',
    description: 'Torrent streaming library for Python. The core library powering torrent-dl, designed for building streaming torrent applications.',
    language: 'Python',
    technologies: ['Python', 'libtorrent'],
    githubUrl: 'https://github.com/animeshkundu/pyflix',
    stars: 14,
    forks: 3,
    featured: false,
    category: 'python-utilities',
    highlights: ['Reusable Library', 'Stream Support'],
  },
  {
    id: 'pyscrape',
    name: 'pyscrape',
    title: 'PyScrape',
    description: 'Headless web scraper with JavaScript rendering for Python. Includes HTTP API for easy integration. Navigate the JavaScript-heavy web from your terminal or scripts.',
    language: 'Python',
    technologies: ['Python', 'Qt5/WebKit', 'HTTP API'],
    githubUrl: 'https://github.com/animeshkundu/pyscrape',
    stars: 4,
    featured: false,
    category: 'python-utilities',
    highlights: ['JS Rendering', 'HTTP API', 'PyPI Package'],
  },
];

export const LIVE_DEMOS: Demo[] = [
  {
    id: 'mermaid-editor',
    name: 'mermaid-editor',
    title: 'Mermaid Editor',
    url: 'https://animeshkundu.github.io/mermaid-editor',
    description: 'Create beautiful diagrams with live preview',
  },
  {
    id: 'pdf-viewer',
    name: 'pdf-viewer',
    title: 'PDF Editor',
    url: 'https://animeshkundu.github.io/pdf-viewer',
    description: 'View, annotate, and edit PDFs in your browser',
  },
  {
    id: 'gist-preview',
    name: 'gist-preview',
    title: 'Gist Preview',
    url: 'https://animeshkundu.github.io/gist-preview',
    description: 'Render GitHub gists with React support',
  },
  {
    id: 'saz-viewer',
    name: 'saz-viewer',
    title: 'SAZ Viewer',
    url: 'https://animeshkundu.github.io/saz-viewer',
    description: 'Inspect Fiddler network captures',
  },
  {
    id: 'har-viewer',
    name: 'har-viewer',
    title: 'HAR Viewer',
    url: 'https://animeshkundu.github.io/har-viewer',
    description: 'Analyze HTTP archive files',
  },
];

export const SKILLS = [
  { name: 'TypeScript', level: 95, category: 'Languages' },
  { name: 'JavaScript', level: 95, category: 'Languages' },
  { name: 'Python', level: 90, category: 'Languages' },
  { name: 'React', level: 95, category: 'Frameworks' },
  { name: 'Vite', level: 90, category: 'Frameworks' },
  { name: 'Tailwind CSS', level: 90, category: 'Frameworks' },
  { name: 'Node.js', level: 85, category: 'Frameworks' },
  { name: 'Web Extensions', level: 85, category: 'Technologies' },
  { name: 'Monaco Editor', level: 80, category: 'Technologies' },
  { name: 'GitHub Actions', level: 85, category: 'DevOps' },
  { name: 'Vitest', level: 85, category: 'Testing' },
];

export const STATS = {
  totalStars: 220,
  totalRepos: 19,
  yearsCoding: 10,
  openSourceProjects: 19,
};
